export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS"
export const CREATE_CUSTOMER_FAIL = "CREATE_CUSTOMER_FAIL"

export const LIST_CUSTOMER_SUCCESS = "LIST_CUSTOMER_SUCCESS"
export const LIST_CUSTOMER_FAIL = "LIST_CUSTOMER_FAIL"

export const SHOW_CUSTOMER_SUCCESS = "SHOW_CUSTOMER_SUCCESS"
export const SHOW_CUSTOMER_FAIL = "SHOW_CUSTOMER_FAIL"

export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS"
export const UPDATE_CUSTOMER_FAIL = "UPDATE_CUSTOMER_FAIL"

export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS"
export const DELETE_CUSTOMER_FAIL = "DELETE_CUSTOMER_FAIL"

export const DELETE_ALL_CUSTOMER_SUCCESS = "DELETE_ALL_CUSTOMER_SUCCESS"
export const DELETE_ALL_CUSTOMER_FAIL = "DELETE_ALL_CUSTOMER_FAIL"

export const SEARCH_CUSTOMER_SUCCESS = "SEARCH_CUSTOMER_SUCCESS"
export const SEARCH_CUSTOMER_FAIL = "SEARCH_CUSTOMER_FAIL"